[env]
PKG_CONFIG_PATH = { value = "/usr/local/lib/pkgconfig", force = true }
PKG_CONFIG = { value = "/opt/homebrew/bin/pkg-config", force = true }

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-Wl,-rpath,/usr/local/lib"]
